name: Build and Push Docker Image to ECR

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
