name: 'Configure AWS Credentials'
description: 'Configures AWS credentials for authentication'

inputs:
  aws-region:
    description: 'AWS region'
    required: true
    type: string
    default: us-east-1

runs:
  using: 'composite'
  steps:
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ inputs.aws-region }}