name: Push to ECR AWS
on:
  workflow_run:
    workflows: ["Push to ECR"]
    types:
      - completed

jobs:
  push-to-ecr:
    name: Push to ECR AWS
    runs-on: ubuntu-latest
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
