name: Push to ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  ECR_REGISTRY: 806379772007.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: shipping-service
  AWS_REGION: us-east-1

jobs:
  call-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
  call-config:
    needs: call-check
    name: Configure AWS Credentials
    uses: ./.github/actions/configure-aws-credentials
    with:
      aws-region: ${{ env.AWS_REGION }}
    
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          
  call-login-ecr:
    needs: call-config
    name: Login to Amazon ECR
    uses: ./.github/actions/login-to-ecr

  call-build-image-to-ecr:
    needs: call-login-ecr
    name: Build and push Docker image to ECR
    uses: ./.github/actions/build-and-push-docker
    with:
      context: .
      push: true
      tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
