name: Push to ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  ECR_REGISTRY: 806379772007.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: shipping-service
  AWS_REGION: us-east-1

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials.yml
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: ./.github/actions/login-to-ecr.yml

      - name: Build and push Docker image to ECR
        uses: ./.github/actions/build-and-push-docker.yml
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
