name: Push to ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  check-repo:
    name: Check Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  unit-test:
    needs: check-repo
    name: Pruebas Unitest
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test Java
        run: echo "Hola UT Java"

  code-test:
    needs: check-repo
    name: Prueba code static
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube
        run: echo "Hola SonarQube"

  buil-push-ecr:
    needs: [unit-test, code-test]
    name: Etapa ECR AWS
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
