name: Push to ECR

on:
  push:
    branches:
      - main
      - feature/*

env:
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  check_repo:
    name: Check Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  configure_aws_credentials:
    needs: check_repo
    name: Configure AWS credentials
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Store AWS credentials
        uses: actions/upload-artifact@v2
        with:
          name: aws-credentials
          path: ${{ runner.temp }}/aws-credentials

  login_to_ecr:
    needs: configure_aws_credentials
    name: Login to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      - name: Download AWS credentials
        uses: actions/download-artifact@v2
        with:
          name: aws-credentials
          path: ${{ runner.temp }}/aws-credentials

      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_CONFIG_FILE: ${{ runner.temp }}/aws-credentials/config

  build_and_push_to_ecr:
    needs: login_to_ecr
    name: Build and Push ECR
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
