name: Main WorkFlow

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

env:
  ECR_REGISTRY: 806379772007.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: shipping-service
  AWS_REGION: us-east-1

jobs:
  call-setup:
    name: Call Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  call-config:
    needs: call-setup
    name: Configurate AWS Credentials
    uses: ./.github/actions/config.yml

  call-push-to-ecr:
    needs: call-config
    name: Push to ECR AWS
    uses: ./.github/actions/ecr.yml
